--- 
title: "officedown Example"
author: "David Gohel"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
biblio-style: apalike
link-citations: yes
description: "This is a minimal example of using the officedown package to write a Word document."
---

```{r include=FALSE}
library(knitr)
library(officedown)
library(officer)
library(flextable)
library(magrittr)
opts_chunk$set(echo = TRUE)
fp <- fp_par(text.align = "center", padding = 20, border.bottom = fp_border())
ft <- fp_text(font.size = 12, bold = TRUE, color = "#C32900", font.family = "Cambria")
```


# Prerequisites

This is a _sample_ book written in **Markdown**. You can use anything that Pandoc's Markdown supports.

The **bookdown** package can be installed from CRAN or Github:

```{r eval=FALSE}
install.packages("bookdown")
```


The `r ftext("officedown", ft)` package can be installed from CRAN or Github: `r fp`

```{r eval=FALSE}
install.packages("officedown")
# or the development version
# remotes::install_github("davidgohel/officedown")
```


