---
date: "`r Sys.Date()`"
author: "Your Name"
title: "Untitled"
output: 
  bookdown::markdown_document2:
    base_format: "officedown::rdocx_document"
    reference_docx: template.docx
    lists:
      ol.style: Default ol
      ul.style: Default ul
---

```{r setup, include=FALSE}
library(officer)
library(officedown)
library(knitr)
opts_chunk$set(echo = TRUE, fig.cap = TRUE)
```


## Table list

```{r echo=FALSE}
block_toc(style = "Table Caption")
```

## Figure list

```{r echo=FALSE}
block_toc(style = "Image Caption")
```


<!---CHUNK_PAGEBREAK--->

## Tables 

### Table 1


```{r tab.cap="caption 1", tab.id="mtcars"}
head(mtcars)
```

### Table 2

```{r tab.cap="iris", tab.width=.7}
head(iris)
```

### Table 3

```{r tab.cap="cars", tab.id="cars", tab.width=.3}
head(cars)
```


## Figures 


### Figure 1

```{r fig.cap="A boxplot", fig.id = "boxplot"}
boxplot(1:8)
```

### Figure 3

```{r}
barplot(1:8)
```

## References

see \@ref(fig:boxplot) and \@ref(tab:mtcars)!


* Dummy item
    * Dummy item
    * Dummy item
        * Dummy item
        * Dummy item
            * Dummy item
            * Dummy item
            * Dummy item
        * Dummy item
    * Dummy item
* Dummy item
* Dummy item

1. Dummy item
    1. Dummy item
        1. Dummy item
            1. Dummy item
    1. Dummy item
        1. Dummy item
        1. Dummy item
    1. Dummy item
1. Dummy item

