# sections ----

#' @title section
#'
#' @description Add a section as a block output in an R
#' Markdown document. A section affects preceding paragraphs
#' or tables.
#'
#' @details
#' A section starts at the end of the previous section (or the beginning of
#' the document if no preceding section exists), and stops where the section is declared.
#' @param w,h width and height in inches of the section page. This will
#' be ignored if the default section (of the `reference_docx` file)
#' already has width and height.
#' @export
#' @rdname sections
#' @name sections
#' @importFrom officer block_section prop_section
block_section_continuous <- function( ){
  block_section(prop_section(type = "continuous"))
}

#' @export
#' @rdname sections
#' @importFrom officer page_size
#' @param break_page break page type. It defines how the contents of the section will be
#' placed relative to the previous section. Available types are "evenPage"
#' (begins on the next, "nextPage" (begins on the following page), "oddPage"
#' (begins on the next odd-numbered page).
block_section_landscape <- function( w = 21 / 2.54, h = 29.7 / 2.54, break_page = "oddPage" ){
  block_section(prop_section(
    page_size = page_size(width = w, height = h, orient = "landscape"),
    type = break_page))
}

#' @export
#' @rdname sections
block_section_portrait <- function( w = 21 / 2.54, h = 29.7 / 2.54, break_page = "oddPage"){
  block_section(prop_section(
    page_size = page_size(width = w, height = h, orient = "portrait"),
    type = break_page))
}

#' @export
#' @param widths columns widths in inches. If 3 values, 3 columns
#' will be produced.
#' @param space space in inches between columns.
#' @param sep if TRUE a line is separating columns.
#' @rdname sections
#' @importFrom officer section_columns
block_section_columns <- function(widths = c(2.5,2.5), space = .25, sep = FALSE){
  block_section(prop_section(
    section_columns = section_columns(widths = widths, space = space, sep = sep),
    type = "continuous"))
}


# misc ----

#' @export
#' @title pour the content of a docx file
#' @description Pour the content of a docx file in the resulting docx
#' generated by the main R Markdown document.
#' @param docx_file external docx file path
block_pour_docx <- function(docx_file){
  str <- paste0("<w:altChunk r:id=\"", docx_file, "\"/>")
  class(str) <- "ooxml"
  str
}

